-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmqB49U01VFM3yXWG
a1WicPwNeufg+Ctc+rd/idvxwzSgCgYIKoZIzj0DAQehRANCAAQArVB8eohzQIxC
j7S9vFoPdl7ZqHbx5iQ4Nqr4g7RUZUPn44YhqvGjpJy2E6/AcTcMB5fhy//Vbjge
ztJEvd1q
-----END PRIVATE KEY-----